networks:
  app_network:


services:

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_USER: appuser
      MYSQL_PASSWORD: abc123
    networks:
      - app_network
    ports:
      - 3306:3306
    
  application:
    build: .
    environment:
      AUTH_TOKEN: myAuthToken
      DATABASE_HOST: database
      DATABASE_USER: root
      DATABASE_PASS: 123456
      DATABASE_NAME: todo
    networks:
      - app_network
    volumes:
      - .:/app/to-do-list
    ports:
      - 3000:3000
    depends_on:
      - database
    restart: on-failure
    command: sh -c "npm run knex && npm run start && knex migrate:up && node index.js"

  